import { goBack } from '../utils/nav'
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity } from 'react-native'

// Juridiskt dokument – hålls på engelska och alltid i ljust läge (som de publika
// webbsidorna), oberoende av appspråk/tema. OBS: mall – låt en jurist granska
// texten och fyll i företagsuppgifterna innan appen börjar säljas.
const C = { bg: '#FEFAF8', primary: '#402D21', secondary: '#6C4D38' }

const SECTIONS: { title: string; body: string }[] = [
  {
    title: '1. About the service',
    body: 'Skrud is a digital wardrobe service that helps you organise your clothes and get AI-generated outfit and style suggestions. By creating an account you agree to these terms.',
  },
  {
    title: '2. Your account',
    body: 'You are responsible for keeping your login details confidential and for activity that happens through your account. You must be at least 16 years old to use the service.',
  },
  {
    title: '3. Your content',
    body: 'You own the images and data you upload. You grant us the right to store and process the content to the extent needed to deliver the service. Do not upload content you don’t have the rights to or that is unlawful.',
  },
  {
    title: '4. AI-generated suggestions',
    body: 'Outfit suggestions, colour analyses and the like are generated by AI and are just that – suggestions. We make no guarantees that they suit you or are free of errors.',
  },
  {
    title: '5. Availability and changes',
    body: 'We strive for high availability but do not guarantee that the service is always free of interruptions. We may change, add or remove features. Material downgrades are announced in advance.',
  },
  {
    title: '6. Termination',
    body: 'You can close your account at any time under My profile → Delete account, which erases all your data. We may suspend accounts that breach these terms.',
  },
  {
    title: '7. Limitation of liability',
    body: 'The service is provided as is. To the extent permitted by law, we are not liable for indirect damages. Nothing in these terms limits your rights as a consumer under mandatory law.',
  },
  {
    title: '8. Contact',
    body: 'Questions about the terms? Contact us at support@skrud.app. Last updated: August 2026.',
  },
]

export default function Terms() {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <TouchableOpacity style={styles.backButton} onPress={() => goBack('/')}>
          <Text style={styles.backButtonText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Terms of use</Text>
        {SECTIONS.map(s => (
          <Text key={s.title}>
            <Text style={styles.heading}>{'\n'}{s.title}{'\n'}</Text>
            <Text style={styles.body}>{s.body}{'\n'}</Text>
          </Text>
        ))}
      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  scroll: { padding: 24, paddingBottom: 60, maxWidth: 720, alignSelf: 'center', width: '100%' },
  backButton: { marginBottom: 16 },
  backButtonText: { fontFamily: 'Lora_400Regular', color: C.secondary, fontSize: 15 },
  title: { fontFamily: 'Poppins_700Bold', fontSize: 32, color: C.primary, marginBottom: 8 },
  heading: { fontFamily: 'Poppins_700Bold', fontSize: 17, color: C.primary, lineHeight: 28 },
  body: { fontFamily: 'Lora_400Regular', fontSize: 14, color: C.secondary, lineHeight: 22 },
})
